import type { Metadata } from "next";
import "./globals.css";

import { ThemeFunction } from './context/ThemeContext';

export const metadata: Metadata = {
  title: "Create first project",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>

        <main className="">
          <ThemeFunction>
            {children}
          </ThemeFunction>
        </main>

      </body>
    </html>
  );
}
